language: python
python:
 - "2.7"
<<<<<<< HEAD
install: 
- pip install -r requirements.txt
- pip install coveralls
script: nosetests
after_success:
coveralls

=======
install: pip install -r requirements.txt
script: nosetests
>>>>>>> origin/develop
